#!/usr/bin/env python3
"""Generate RUNS.md (read-only index) from experiments/runs/*.yaml.

One YAML file per run is the source of truth (merge-safe across agents);
RUNS.md is a generated overview only. See CONVENTIONS.md §1.

Usage:  python scripts/gen_runs_md.py
"""
from __future__ import annotations

import glob
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml not installed in this env: `pip install pyyaml`")

REPO = Path(__file__).resolve().parents[1]
RUNS_DIR = REPO / "experiments" / "runs"
OUT = REPO / "RUNS.md"

COLS = ["run_id", "status", "method", "model", "bench", "acc", "owner", "started", "notes"]


def main() -> None:
    rows = []
    for f in sorted(glob.glob(str(RUNS_DIR / "*.yaml"))):
        if os.path.basename(f).startswith("_"):
            continue  # skip _TEMPLATE.yaml
        with open(f) as fh:
            d = yaml.safe_load(fh) or {}
        rows.append({c: d.get(c, "") for c in COLS})

    lines = [
        "# RUNS — experiment index",
        "",
        "> Auto-generated by `scripts/gen_runs_md.py` from `experiments/runs/*.yaml`.",
        "> Do NOT edit by hand — edit the per-run YAML and regenerate.",
        "",
        "| " + " | ".join(COLS) + " |",
        "|" + "|".join(["---"] * len(COLS)) + "|",
    ]
    if rows:
        for r in rows:
            lines.append("| " + " | ".join(str(r[c]) for c in COLS) + " |")
    else:
        lines.append("| _(no runs yet)_ |" + " |" * (len(COLS) - 1))

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} run(s))")


if __name__ == "__main__":
    main()
